### PR TITLE
fixed IAM deletion problem

### LINKED ISSUE #122: Handel-codepipeline deletes shared IAM Role
When you have two version of a pipeline in the same account. (IE different regions, prod pipeline and a dev pipeline). If you delete one of the pipelines it will delete the codebuild build phase role that is used by the other pipelines and break the pipeline.

### PR DESCRIPTION
**Pull request by mxnguyen350**
resolves #122

### CODE REVIEW

File: src/phases/codebuild/index.ts [hunk 1]
```diff
@@ -65,17 +74,28 @@ async function createBuildPhaseServiceRole(accountConfig: AccountConfig, appName
     return iamCalls.createOrUpdateRoleAndPolicy(roleName, ['codebuild.amazonaws.com'], policyArn, policyDocObj);
 }
 
-async function deleteBuildPhaseServiceRole(accountId: string, appName: string) {
-    const roleName = getBuildPhaseRoleName(appName);
-    const policyArn = getBuildPhasePolicyArn(accountId, appName);
+async function deleteBuildPhaseServiceRole(accountConfig: AccountConfig, appName: string) {
+    let roleName;
+    let policyArn;
+    const params = {
```
Comment (dsw88) [inline src/phases/codebuild/index.ts]: Probably move this inside the `try` statement since it looks like it is only used there. You also might want to call it something a bit more unique than `params`; even `getParams` would probably be better.

File: src/phases/codebuild/index.ts [hunk 2]
```diff
@@ -65,17 +74,28 @@ async function createBuildPhaseServiceRole(accountConfig: AccountConfig, appName
...
+        RoleName: `${appName}-${accountConfig.region}-HandelCodePipelineBuildPhase`
+    };
+    try {
```
Comment (dsw88) [inline src/phases/codebuild/index.ts]: Probably put a comment before the try block that tells why we have this old/new role name and that it should be removed at some point in the future.

File: src/phases/codebuild/index.ts [hunk 3]
```diff
@@ -65,17 +74,28 @@ async function createBuildPhaseServiceRole(accountConfig: AccountConfig, appName
...
+        await awsWrapper.iam.getRole(params);
+        roleName = getBuildPhaseRoleName(appName, accountConfig.region);
+        policyArn = getBuildPhasePolicyArn(accountConfig, appName);
+    } catch (e) {
```
Comment (dsw88) [inline src/phases/codebuild/index.ts]: This only deletes one or the other, but if you update an existing pipeline, it means both roles will be present when deleting it. It might be good to delete both of them for good measure. I believe these delete functions are idempotent, meaning they should be successful even if you're deleting something that is already gone.

File: src/phases/codebuild/index.ts [hunk 4]
```diff
@@ -65,17 +74,38 @@ async function createBuildPhaseServiceRole(accountConfig: AccountConfig, appName
...
+        await awsWrapper.iam.getRole(getParams);
+        roleName = getBuildPhaseRoleName(appName, accountConfig.region);
+        policyArn = getBuildPhasePolicyArn(accountConfig, appName);
+        await iamCalls.detachPolicyFromRole(roleName, policyArn);
+        await iamCalls.deletePolicy(policyArn);
+        await iamCalls.deleteRole(roleName);
+    } catch (e) {
+        console.log(`No role exists with the new naming convention`);
+    }
+    try {
```
Comment (dsw88) [inline src/phases/codebuild/index.ts]: I don't think you need a try/catch around these delete calls, because I think the delete calls won't throw an error if the item isn't there. They'll just return true because if it's not there it means it is deleted, so their mission was accomplished. :) Try removing them and doing a test pipeline deploy/delete just to be sure though.
